[package]
name = "woopaper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.2"
rand = "0.8.5"
opener = "0.5.0"
colored = "2"
trash = "3.0.0"
notify-rust = "4.6"
